version: '3.7'

networks:
  app_network:

services:
  currency-conversion:
    image: neoradu/mmv2-currency-conversion-service:0.0.11-SNAPSHOT
    ports:
      - "8100:8100"
    networks:
      - app_network
    environment:
      CURRENCY_EXCHANGE_SERVICE_HOST: currency-exchange


  currency-exchange:
    image: neoradu/mmv2-currency-exchange-service:0.0.11-SNAPSHOT
    networks:
      - app_network
